import { Package, Shirt, Sparkles } from "lucide-react";

export const ClothesOffersData = [
  // ========== ليجن ريب ==========
  {
    name: "3 ليجن ريب",
    quantity: 3,
    price: 270,
    badge: "عرض خاص",
    badgeColor: "from-[#e13485] to-[#c01e6f]",
    icon: <Package className="w-4 h-4" />,
    savings: -15,
    originalPrice: 255,
    unit: "ليجن ريب",
    popular: false,
    tabType: "legging",
  },
  {
    name: "4 ليجن ريب",
    quantity: 4,
    price: 340,
    badge: "عرض خاص",
    badgeColor: "from-[#e13485] to-[#c01e6f]",
    icon: <Package className="w-4 h-4" />,
    savings: 0,
    originalPrice: 340,
    unit: "ليجن ريب",
    popular: false,
    tabType: "legging",
  },
  {
    name: "5 ليجن ريب",
    quantity: 5,
    price: 425,
    badge: "الأكثر طلباً",
    badgeColor: "from-[#e13485] to-[#c01e6f]",
    icon: <Package className="w-4 h-4" />,
    savings: 0,
    originalPrice: 425,
    unit: "ليجن ريب",
    popular: true,
    tabType: "legging",
  },
  {
    name: "6 ليجن ريب",
    quantity: 6,
    price: 480,
    badge: "عرض مميز",
    badgeColor: "from-[#e13485] to-[#c01e6f]",
    icon: <Package className="w-4 h-4" />,
    savings: 30,
    originalPrice: 510,
    unit: "ليجن ريب",
    popular: false,
    tabType: "legging",
  },
  {
    name: "8 ليجن ريب",
    quantity: 8,
    price: 600,
    badge: "الأكثر طلباً",
    badgeColor: "from-[#e13485] to-[#c01e6f]",
    icon: <Package className="w-4 h-4" />,
    savings: 80,
    originalPrice: 680,
    unit: "ليجن ريب",
    popular: true,
    tabType: "legging",
  },
  {
    name: "12 ليجن ريب",
    quantity: 12,
    price: 840,
    badge: "أفضل قيمة",
    badgeColor: "from-[#e13485] to-[#c01e6f]",
    icon: <Sparkles className="w-4 h-4" />,
    savings: 180,
    originalPrice: 1020,
    unit: "ليجن ريب",
    popular: true,
    tabType: "legging",
  },

  // ========== الشورت ==========
  {
    name: "2 شورت",
    quantity: 2,
    price: 199,
    badge: "عرض خاص",
    badgeColor: "from-[#ff8c93] to-[#e13485]",
    icon: <Shirt className="w-4 h-4" />,
    savings: 21,
    originalPrice: 220,
    unit: "شورت",
    popular: false,
    tabType: "short",
  },
  {
    name: "3 شورت",
    quantity: 3,
    price: 255,
    badge: "الأكثر طلباً",
    badgeColor: "from-[#ff8c93] to-[#e13485]",
    icon: <Shirt className="w-4 h-4" />,
    savings: 75,
    originalPrice: 330,
    unit: "شورت",
    popular: true,
    tabType: "short",
  },
  {
    name: "4 شورت",
    quantity: 4,
    price: 320,
    badge: "أفضل قيمة",
    badgeColor: "from-[#ff8c93] to-[#e13485]",
    icon: <Shirt className="w-4 h-4" />,
    savings: 120,
    originalPrice: 440,
    unit: "شورت",
    popular: true,
    tabType: "short",
  },

  // ========== التوبات ==========
  {
    name: "2 توب",
    quantity: 2,
    price: 490,
    badge: "عرض خاص",
    badgeColor: "from-[#a0105a] to-[#e13485]",
    icon: <Sparkles className="w-4 h-4" />,
    savings: 70,
    originalPrice: 560,
    unit: "توب",
    popular: false,
    tabType: "top",
  },
  {
    name: "3 توب",
    quantity: 3,
    price: 710,
    badge: "الأكثر طلباً",
    badgeColor: "from-[#a0105a] to-[#e13485]",
    icon: <Sparkles className="w-4 h-4" />,
    savings: 130,
    originalPrice: 840,
    unit: "توب",
    popular: true,
    tabType: "top",
  },
  {
    name: "4 توب",
    quantity: 4,
    price: 880,
    badge: "أفضل قيمة",
    badgeColor: "from-[#a0105a] to-[#e13485]",
    icon: <Sparkles className="w-4 h-4" />,
    savings: 240,
    originalPrice: 1120,
    unit: "توب",
    popular: true,
    tabType: "top",
  },
];